# Generated by Django 3.2 on 2021-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registracnizn', models.CharField(max_length=20)),
                ('znackatyp', models.CharField(max_length=100)),
                ('najetekm', models.IntegerField()),
                ('datkontroly', models.DateField()),
            ],
        ),
    ]
